---
- name: install packages
  ansible.builtin.apt:
    name:
      - make
      - python3-pip
      - tox
    update_cache: true
  become: true

- name: alternatives python
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
  become: true

- import_tasks: _install_docker.yml
  become: true

- import_tasks: _install_k3s.yml
  become: true

- name: install pip packages
  ansible.builtin.pip:
    name:
      - docker==5.0.3
      # - tox==3.24.5
