---
# ansible-builder
- name: create working directory
  ansible.builtin.file:
    state: directory
    path: "{{ BASE_DIR }}/ansible-builder"

- name: clone repository
  ansible.builtin.git:
    repo: https://github.com/ansible/ansible-builder.git
    dest: "{{ BASE_DIR }}/ansible-builder"
    version: 1.0.1

- name: build image
  community.general.make:
    chdir: "{{ BASE_DIR }}/ansible-builder"
    target: image
