---
# awx-ee
- name: create working directory
  ansible.builtin.file:
    state: directory
    path: "{{ BASE_DIR }}/awx-ee"

- name: clone repository
  ansible.builtin.git:
    repo: https://github.com/ansible/awx-ee.git
    dest: "{{ BASE_DIR }}/awx-ee"
    version: "{{ awx_ee_version }}"

- name: build awx-ee
  ansible.builtin.command:
    cmd: tox -edocker
    chdir: "{{ BASE_DIR }}/awx-ee"
  become: true # ないと"ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'"で動かないため回避策

- name: push container image
  community.docker.docker_image:
    name: quay.io/ansible/awx-ee
    repository: "zakihmkc/awx-ee:{{ awx_ee_version }}"
    push: true
    source: local
    force_tag: true
  # vars:
  #   ansible_python_interpreter: /home/ubuntu/venv/awx-build/bin/python
