---
- name: uninstall old versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: install packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: add docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  # gpg --dearmor -o と結果が異なるが後続の動作に影響なかった

- name: get machine architecture
  ansible.builtin.command: dpkg --print-architecture
  register: arch_result
  changed_when: false

- name: add apt repository
  vars:
    arch: "{{ arch_result.stdout }}"
    dist: "{{ ansible_distribution_release }}"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ dist }} stable"
    filename: docker

- name: install docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: enabled docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: update group
  ansible.builtin.user:
    name: ubuntu
    groups:
      - docker
    append: true

- name: reset connection
  ansible.builtin.meta: reset_connection
