---
- name: create namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    name: awx
    kind: Namespace
    api_version: v1

- name: create ingress resource
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    resource_definition:
      apiVersion: "networking.k8s.io/v1"
      kind: Ingress
      metadata:
        name: awx-ingress
        namespace: awx
        # annotations:
        #   kubernetes.io/ingress.class: traefik-lb
      spec:
        ingressClassName: traefik-lb
        rules:
        - host: awx03.jp-z.jp
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: awx-demo-service
                  port:
                    number: 80
- name: deploy awx-demo
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    resource_definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx-demo
        namespace: awx
      spec:
        service_type: nodeport
        image: zakihmkc/awx
        image_version: "{{ awx_version }}"
        image_pull_policy: Always
        ee_images:
          - name: awx-ee-arm64
            image: zakihmkc/awx-ee:0.6.0
          - name: AWX EE (latest)
            image: zakihmkc/awx-ee:0.6.0
        control_plane_ee_image: zakihmkc/awx-ee:0.6.0
        ingress_type: ingress
        hostname: awx03.jp-z.jp
        # web_resource_requirements:
        #   requests:
        #     cpu: 400m
        #     memory: 2Gi
        #   limits:
        #     cpu: 400m
        #     memory: 2Gi
        # task_resource_requirements:
        #   requests:
        #     cpu: 400m
        #     memory: 1Gi
        #   limits:
        #     cpu: 400m
        #     memory: 1Gi
        # ee_resource_requirements:
        #   requests:
        #     cpu: 400m
        #     memory: 1Gi
        #   limits:
        #     cpu: 400m
        #     memory: 1Gi
