---
- name: create namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    name: "{{ awx_namespace }}"
    kind: Namespace
    api_version: v1

- name: deploy awx-demo
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    template: awx-demo.yaml.j2
