---
- name: define repository url
  set_fact:
    operator_image_repository: "{{ ((registry_url is defined) | ternary(registry_url, ''), registry_username, 'awx-operator') | path_join }}"
  when: registry_username is defined

- name: deploy awx-operator
  community.general.make:
    chdir: "{{ BASE_DIR }}/awx-operator"
    target: deploy
    params:
      IMG: "{{ operator_image_repository }}:{{ operator_version }}"
  environment:
    NAMESPACE: "{{ awx_namespace }}"
