---
- name: deploy awx-operator
  community.general.make:
    chdir: "{{ BASE_DIR }}/awx-operator"
    target: deploy
    params:
      IMG: "{{ operator_image_repository }}:{{ operator_version }}"
  environment:
    NAMESPACE: "{{ awx_namespace }}"
