---
# awx-operator
- name: define repository url
  set_fact:
    operator_image_repository: "{{ ((registry_url is defined) | ternary(registry_url, ''), registry_username, 'awx-operator') | path_join }}"
  when: registry_username is defined

- name: create working directory
  ansible.builtin.file:
    state: directory
    path: "{{ BASE_DIR }}"

- name: clone repository
  ansible.builtin.git:
    repo: https://github.com/ansible/awx-operator.git
    dest: "{{ BASE_DIR }}/awx-operator"
    version: "{{ operator_version }}"
    force: true # デプロイ時にkustomizeの更新があり再cloneできないため

# - name: build awx-operator
#   ansible.builtin.shell:
#     cmd: |
#       make docker-build IMG=zakihmkc/awx-operator:0.17.0
# #      make docker-build IMAGE_TAG_BASE=zakihmkc/awx-operator VERSION=0.17.0-arm
#     chdir: "{{ BASE_DIR }}/awx-operator"

- name: build awx-operator
  community.general.make:
    chdir: "{{ BASE_DIR }}/awx-operator"
    target: docker-build
    params:
      IMG: "{{ operator_image_repository }}:{{ operator_version }}"

- name: push container image
  community.docker.docker_image:
    name: "{{ operator_image_repository }}:{{ operator_version }}"
    repository: "{{ operator_image_repository }}:{{ operator_version }}"
    push: true
    source: local

# - name: deploy awx-operator
#   community.general.make:
#     chdir: "{{ BASE_DIR }}/awx-operator"
#     target: deploy
#     params:
#       IMG: zakihmkc/awx-operator:0.17.0
